FROM archlinux:base-devel

# Init pacman keyring to for proper download of packages
RUN pacman-key --init && pacman-key --populate archlinux

# Install and run reflector for finding the best mirrors
RUN pacman -Sy --noconfirm reflector \
    && reflector \
      --latest 20 \
      --protocol https \
      --sort rate \
      --save /etc/pacman.d/mirrorlist \
    && pacman -Rns --noconfirm reflector

# Install base-devel, fish, micro, and a few extra dev essentials
RUN pacman -Syu --noconfirm \
    && pacman -S --noconfirm \
        fish \
        zsh \
        micro \
        nano \
        helix \
        sudo \
        git \
        cmake \
        less \
        wl-clipboard \
        openssh \
        wget \
        ripgrep \
        fd \
        npm \
        unzip \
        fzf \
        ca-certificates \
    && pacman -Scc --noconfirm \
    && rm -rf /var/cache/pacman/pkg/*

# Setup ssh for remote development
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config \
    && echo "PermitRootLogin no" >> /etc/ssh/sshd_config \
    && echo "PermitUserEnvironment yes" >> /etc/ssh/sshd_config \
    && ssh-keygen -A

EXPOSE 22

# Add default user
RUN useradd -m -d /home/dev -s /bin/bash dev \
	&& echo "dev:dev" | chpasswd \
	&& echo "dev ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Setup the entrypoint
COPY entrypoint.sh /var/entrypoint.sh
RUN chmod +x /var/entrypoint.sh

ENTRYPOINT ["/var/entrypoint.sh"]

# Set default user
USER dev

# Install yay
RUN git clone https://aur.archlinux.org/yay-bin.git /tmp/yay \
    && cd /tmp/yay \
    && makepkg -si --noconfirm

# Set a working directory inside the container
WORKDIR /workspace
