FROM archlinux:latest

# Install base-devel, fish, micro, and a few extra dev essentials
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
        base-devel \
        fish \
        zsh \
        micro \
        nano \
        sudo \
        git \
        cmake \
        less \
        wl-clipboard \
        openssh \
    && pacman -Scc --noconfirm \
    && rm -rf /var/cache/pacman/pkg/*

RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config \
    && echo "PermitRootLogin no" >> /etc/ssh/sshd_config

RUN ssh-keygen -A

EXPOSE 22

RUN useradd -m -d /home/dev -s /bin/bash dev \
	&& echo "dev:dev" | chpasswd \
	&& echo "dev ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Set a working directory inside the container
WORKDIR /workspace

COPY entrypoint.sh /var/entrypoint.sh
RUN chmod +x /var/entrypoint.sh

ENTRYPOINT ["/var/entrypoint.sh"]

USER dev
